environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      DISTRIBUTIONS: "bdist_wheel"

# Branches to build:
branches:
  # whitelist
  only:
    - refactor

# Operating system (build VM template)
os: Visual Studio 2017

# Init:
init:
  - "echo %PYTHON%"
  -  call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

# Install:
install:
  # - "%PYTHON%/Scripts/pip.exe install colorama"

# Build:
build_script:
  # - cmd: example-run-Win-VS2015.bat
  - git submodule update --init --recursive
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: "%PYTHON%/python.exe build.py all -DTRAVIS=1"

# Notifications:
notifications:
  - provider: Email
    to:
      - fuiripecn@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
