language: cpp
- compiler: gcc
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.9
      env: COMPILER=g++-4.9
  python:
    - "2.7"
  install:
  - sudo apt-get update
  - sudo apt-get install libcppunit-dev libcppunit-1.12-1
script:
  - python2.7 build.py
