# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
addons:
  apt:
    sources:
      # add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
    packages:
      # install toolchains
      - g++-4.9
      env: COMPILER=g++-4.9
language: cpp
compiler: gcc
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get install libcppunit-dev libcppunit-1.12-1
script:
  - python2.7 build.py
