language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
#          packages:
#            - clang-3.6
#      env: COMPILER=clang++-3.6
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#          packages:
#            - clang-3.7
#      env: COMPILER=clang++-3.7
python:
  - "3.5"
before_install:
  - sudo apt-get install lcov rubygems
  - gem install lcoveralls
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
#  - sudo apt-get update -qq
#  - sudo pip install codecov
  - cmake --version
script:
  - git submodule update --init --recursive
  - cmake --version
  - cmake .
  - make
#  - python3 build.py test
after_success:
  - codecov
  - lcoveralls
