language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
#            - george-edison55-precise-backports
            - deadsnakes
            - kubuntu-backports
          packages:
            - g++-7
            - python3.5
            - python3.5-dev
            - python3.5-venv
            - libglu1-mesa-dev
            - libxxf86vm-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libx11-dev
            - cmake
            - cmake-data
      env: COMPILER=g++-7
    # - compiler: clang
      # addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
            # - llvm-toolchain-trusty-5.0
          # packages:
            # - clang-5.0
            # - python3.5
            # - python3.5-dev
            # - python3.5-venv
            # - libglu1-mesa-dev
            # - libxxf86vm-dev
            # - libxrandr-dev
            # - libxinerama-dev
            # - libxcursor-dev
            # - libxi-dev
            # - libx11-dev
            # - cmake
            # - cmake-data
      # env: COMPILER=clang++-5.0
python:
  - "3.5"
before_install:
#  - sudo apt-get install lcov rubygems
#  - gem install lcoveralls
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
#  - sudo apt-get update -qq
#  - sudo pip install codecov
  - cmake --version
script:
  # - git submodule update --init --recursive
  - cmake --version
  - cmake . -DBUILD_TESTS=ON
  - make
after_success:
#  - codecov
#  - lcoveralls
