language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake
            - cmake-data
      env: COMPILER=g++-7
    - compiler: clang
      addons:
        apt:
          sources:
#            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
#            - llvm-toolchain-precise-3.7
          packages:
            - clang-5.0
      env: COMPILER=clang++-5.0
python:
  - "3.5"
before_install:
#  - sudo apt-get install lcov rubygems
#  - gem install lcoveralls
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
#  - sudo apt-get update -qq
#  - sudo pip install codecov
  - cmake --version
script:
  - git submodule update --init --recursive
  - cmake --version
  - cmake .
  - make
after_success:
#  - codecov
#  - lcoveralls
