cc_library(
    name = "ponos",
    srcs = glob(["ponos/**/*.cpp"]),
    hdrs = glob(["ponos/**/*.h", "ponos/*.h", "ponos/**/*.inl"]),
    includes = ["."],
    visibility = ["//visibility:public"],
)