#include <aergia.h>
#include <hercules.h>
#include <ponos.h>
#include "clock.hpp"
#include "game.hpp"
#include "game_object.hpp"
#include "component_interface.h"
#include "graphics_component.hpp"
#include "input_component.hpp"
#include "physics_component.hpp"
