set(CATCH_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
# add_library(Catch2::Catch IMPORTED INTERFACE)
# set_property(Catch2::Catch PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${CATCH_INCLUDE_DIR}")

set(CATCH2_INCLUDES "${CMAKE_CURRENT_SOURCE_DIR}/ext")
