add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/ext/glad" "ext_build/glad")
# set_target_properties(glad PROPERTIES EXCLUDE_FROM_ALL 1 EXCLUDE_FROM_DEFAULT_BUILD 1)
# target_compile_definitions(glad PUBLIC GLAD_GENERATOR="c++")
set(GLAD_INCLUDES "${CMAKE_CURRENT_SOURCE_DIR}/ext/glad/include")
IF (CMAKE_BUILD_TYPE MATCHES DEBUG)
    set(GLAD_LIBS "${CMAKE_BINARY_DIR}/ext_build/glad/libgladd.so")
ENDIF (CMAKE_BUILD_TYPE MATCHES DEBUG)
IF (CMAKE_BUILD_TYPE MATCHES RELEASE)
    set(GLAD_LIBS "${CMAKE_BINARY_DIR}/ext_build/glad/libglad.so")
ENDIF (CMAKE_BUILD_TYPE MATCHES RELEASE)
