name: gcc-compiler-ubuntu-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build ubuntu/gcc
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.19.x'

      - name: Configure & build
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=ON
          make -j8

      - name: Test
        run: |
            cd build/ponos/tests
            ./ponos_tests

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}




